import {Ident} from './idents';

const INSERT_PREFIX = '+';
const REMOVE_PREFIX = '-';
const SEPARATOR = '/';

/**
 * The kind of operation.
 */
export enum OpKind {

  /**
   * The insertion of a value.
   */
  Insert = 1,

  /**
   * The removal of a value.
   */
  Remove = 2,
}

/**
 * An operation that can be applied to a KSeq.
 */
export abstract class Op {

  /**
   * Converts an encoded string to an Op of the correct type.
   * @param str The encoded string.
   * @returns An instance of the encoded Op.
   */
  static parse(str: string): Op {
    const kind = str[0];
    switch (kind) {
      case INSERT_PREFIX: return InsertOp.parse(str);
      case REMOVE_PREFIX: return RemoveOp.parse(str);
      default: throw new Error(`First character must be ${INSERT_PREFIX} or ${REMOVE_PREFIX}`);
    }
  }

  /**
   * The kind of operation.
   */
  kind: OpKind;

  /**
   * The name of the replica on which the operation was performed.
   */
  replica: string;

  /**
   * A UNIX epoch timestamp for the wall time at which the operation was performed.
   * (Note: since this is generated by the local replica's clock, it is just an
   * approximation and should not be used to create a total order.)
   */
  timestamp: number;

  /**
   * Creates an instance of Op.
   * @param kind      The kind of operation.
   * @param replica   The name of the replica on which the operation was performed.
   * @param timestamp A UNIX epoch timestamp for the wall time when the operation was performed.
   * @returns An instance of Op.
   */
  constructor(kind: OpKind, replica: string, timestamp: number) {
    this.kind = kind;
    this.replica = replica;
    this.timestamp = timestamp;
  }

  /**
   * Encodes the Op as a compact string representation.
   */
  abstract toString(): string;

}

/**
 * An operation that inserts an atom into the sequence with the specified
 * identifier and value.
 */
export class InsertOp extends Op {

  /**
   * Converts an encoded string to an InsertOp.
   * @param str The encoded string.
   * @returns An instance of the encoded InsertOp.
   */
  static parse(str: string): InsertOp {
    const parts = str.substring(1).split(SEPARATOR);
    const value = parts.length > 4 ? parts.slice(3, parts.length).join(SEPARATOR) : parts[3]; // in case our separator was included
    return new InsertOp(parts[0], Number(parts[1]), Ident.parse(parts[2]), JSON.parse(value));
  }

  /**
   * The identifier for the value.
   */
  id: Ident;

  /**
   * The value to insert.
   */
  value: any;

  /**
   * Creates an instance of InsertOp.
   * @param replica   The name of the replica on which the operation was performed.
   * @param timestamp A UNIX epoch timestamp for the wall time when the operation was performed.
   * @param id        The identifier for the value.
   * @param value     The value to insert.
   * @returns An instance of InsertOp.
   */
  constructor(replica: string, timestamp: number, id: Ident, value: any) {
    super(OpKind.Insert, replica, timestamp);
    this.id = id;
    this.value = value;
  }

  /**
   * @inheritdoc
   */
  toString() {
    return `${INSERT_PREFIX}${this.timestamp}${SEPARATOR}${this.replica}${SEPARATOR}${this.id.toString()}${SEPARATOR}${JSON.stringify(this.value)}`;
  }

}

/**
 * An operation that removes an atom with the specified identifer.
 */
export class RemoveOp extends Op {

  /**
   * Converts an encoded string to an RemoveOp.
   * @param str The encoded string.
   * @returns An instance of the encoded RemoveOp.
   */
  static parse(str: string): RemoveOp {
    const [timestamp, replica, id] = str.substring(1).split(SEPARATOR, 3);
    return new RemoveOp(replica, Number(timestamp), Ident.parse(id));
  }

  /**
   * The identifier to remove.
   */
  id: Ident;

  /**
   * Creates an instance of RemoveOp.
   * @param replica   The name of the replica on which the operation was performed.
   * @param timestamp A UNIX epoch timestamp for the wall time when the operation was performed.
   * @param id        The identifier of the atom to remove.
   * @returns An instance of RemoveOp.
   */
  constructor(replica: string, timestamp: number, id: Ident) {
    super(OpKind.Remove, replica, timestamp);
    this.id = id;
  }

  /**
   * @inheritdoc
   */
  toString() {
    return `${REMOVE_PREFIX}${this.timestamp}${SEPARATOR}${this.replica}${SEPARATOR}${this.id.toString()}`;
  }

}
