// Generated by typings
// Source: https://raw.githubusercontent.com/types/npm-basic-auth/6ef4a98dcf8933836878cc45171b154cfe36e00e/index.d.ts
declare module 'basic-auth' {

import {IncomingMessage} from 'http';

class Credentials {
    name: string;
    pass: string;
}

/**
 * Get the basic auth credentials from the given request. The `Authorization`
 * header is parsed and if the header is invalid, `undefined` is returned,
 * otherwise an object with `name` and `pass` properties.
 */
function auth(req: IncomingMessage): Credentials;

export = auth;
}
